name: Run Tests
on: push
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    container:
      # TODO(sean) build local image instead and use to run tests
      image: python:3.8-alpine
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Test package
        run: python3 -m unittest discover
